language: php

php:
 - 7.1

before_script:
# - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.3
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0
 - git clone https://github.com/SirSnyder/pthreads.git -b php/71 --depth=1
 - cd pthreads
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
 - ./tests/travis.sh

notifications:
 email: false
